name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '^12.13.1'

      - name: Install Marp cli
        run: |
          npm i @marp-team/marp-cli --no-save
      - name: Build Marp slide deck
        run: |
          marp --theme monster.css -- monster-in-code.md
        env:
          # Please update URL if you want to use custom domain
          URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}

          # Recommend to set lang for your deck to get better rendering for Open Graph image
          LANG: en-US

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
